### ISSUE TITLE
seems like the package doesn't run on jupyter notebook with py 3.12 at all.

### ISSUE THREAD

**Issue by TsabarM** [koaning/human-learn#81]
for example the 01-function-classifier.ipynb is not working at all
error like:
AttributeError: 'FunctionClassifier' object has no attribute 'classes_'

and the parallel_coordinates(df, label="survived", height=200) command doesn't present the lines of the lables prediction.

why is that?

**Comment by koaning** [comment]
I would need to check that. Just to check, can you confirm that it does work on Python 3.11?

**Comment by TsabarM** [comment]
It works on 3.10. but not as expected. the plots of parallel_coordinates is not as shown in the toutorial.
